development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gatekeeper_development
  pool: 5
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gatekeeper_test
  pool: 5
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: gatekeeper_production
  pool: 5
  username: root
  password: 
